{% set name = "intermol" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shirtsgroup/InterMol/archive/v{{ version }}.tar.gz
  sha256: e59163d47426f0b7cd5e6e5c11ad833ed8d99050e4dc2312d03bbb567b0f437b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - parmed
    - six

test:
  imports:
    - intermol
    - intermol.tests
    - intermol.gromacs
    - intermol.amber
    - intermol.lammps
    - intermol.desmond

about:
  home: https://github.com/shirtsgroup/InterMol
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Conversion tool for molecular simulations
  description: Conversion tool for molecular simulations
  dev_url: https://github.com/shirtsgroup/InterMol

extra:
  recipe-maintainers:
    - mattwthompson
